version: '3'
services:
  go-web-app:
    restart: always
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      # This is required by the URL shortener
      - AUTHENTICATION_KEY=${AUTHENTICATION_KEY}
      # This is required for opening the database file
      # and for the migrations tool (dbmate)
      - DATABASE_URL=${DATABASE_URL}
      # The absolute path to the static assets directory
      - STATIC_DIR=${STATIC_DIR}
      # The absolute path to the templates directory
      - TEMPLATE_BASEDIR=${TEMPLATE_BASEDIR}
      - PORT=${PORT:-8000}
    volumes:
      - "urlshortenerdata:$DATABASE_DIR"
    command:
      - /bin/sh
      - -c
      - |
        /opt/bin/run-migrations.sh
        gourlshortener

volumes:
  urlshortenerdata:
    external: true
      