version: '3'
services:
  go-web-app:
    restart: always
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - AUTHENTICATION_KEY=${AUTHENTICATION_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - DBMATE_MIGRATIONS_DIR=${DBMATE_MIGRATIONS_DIR}
      - DBMATE_SCHEMA_FILE=${DBMATE_SCHEMA_FILE}
      - DBMATE_STRICT=${DBMATE_STRICT}
      - STATIC_DIR=${STATIC_DIR}
      - TEMPLATE_BASEDIR=${TEMPLATE_BASEDIR}
      - PORT=${PORT:-8000}
    volumes:
      - "urlshortenerdata:$DATABASE_DIR"
    command:
      - /bin/sh
      - -c
      - |
        /opt/bin/run-migrations.sh
        gourlshortener

volumes:
  urlshortenerdata:
    external: true
      