app = 'new-go-url-shortener'
primary_region = 'syd'

[build]

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[services.ports]]
  port = 443
  handlers = ["tls", "http"]

[services.ports.http_options.response.headers]
  Clear-Site-Data = "*"
  Content-Security-Policy = "default-src 'self'"
  Referrer-Policy = "origin-when-cross-origin"
  Strict-Transport-Security = "max-age=63072000; includeSubDomains;"
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "sameorigin"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = "app_data"
  destination = "/data"
